# Generated by Django 3.0.2 on 2020-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('kind', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=1)),
            ],
        ),
    ]
